# Generated by Django 4.1.3 on 2022-11-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField(default=1, help_text='En Dolares')),
                ('peso', models.PositiveIntegerField(help_text='En kg')),
                ('tipo', models.CharField(choices=[('VIRTUAL', 'virtual'), ('FISICO', 'fisico')], default='FISICO', max_length=10)),
                ('url_download', models.URLField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
