# Generated by Django 4.1.3 on 2022-12-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_viewpadrehijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nuevo_nombre',
            },
        ),
    ]
