# Generated by Django 4.1.3 on 2022-12-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_nuevonombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevonombre',
            name='a',
            field=models.CharField(db_column='otro_nombre', default='', max_length=50),
        ),
    ]
