# Generated by Django 4.1.3 on 2022-12-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_nuevonombre_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(default='', max_length=60),
        ),
    ]
