# Generated by Django 4.1.3 on 2022-12-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
